### ISSUE TITLE
Validate compatibility with ansible-core 2.19

### ISSUE THREAD

**Issue by samccann** [vyos/vyos.vyos#417]
Copied from ansible-community/ansible-build-data#538

 ansible-core has implemented an extensive rewrite of templating and error handling as part of the [data tagging feature ](https://github.com/ansible/ansible/pull/84621) coming in core-2.19. You can find information about this change in that PR description, as well as in the [core 2.19 porting guide](https://docs.ansible.com/ansible-core/devel/porting_guides/porting_guide_core_2.19.html). 
 
 Please read  [background and testing requests,](https://forum.ansible.com/t/data-tagging-preview-and-testing/40759) which details where you can file potential bugs.

Collections that are part of the Ansible community package MUST test against `ansible-core 2.19` to ensure they continue to work with the updated core. Collections which are not compatible with `ansible-core 2.19`  will be removed from Ansible 12.  You can choose to test against the `stable-2.19` branch, the `devel` branch, the `milestone` branch, or the pre-release/released versions of `ansible-core 2.19` available on [Pypi](https://pypi.org/project/ansible-core/#history).

This should be an ongoing verification/check until the release of core 2.19 to ensure compatibility with any bugfixes or changes that happen until then.

You can find advice from fellow maintainers at [Making a collection compatible with data tagging](https://forum.ansible.com/t/making-a-collection-compatible-with-data-tagging/41717), and we welcome your additions to that forum topic.
 
 **Note:** You are not required to implement data tagging as part of this request, though we do recommend you consider where it can improve the quality of your collection. This issue is focused on ensuring you have verified your collection works with `ansible-core 2.19` in order to remain included in the Ansible 12 community package.
 
 We ask that you resolve any problems and link those PRs to this issue. If you do not find any problems with your integration/unit testing, please provide that comment and a pointer to your test results before closing this issue as done.
 
 You can reach out on the [Ansible forum](https://forum.ansible.com/t/data-tagging-preview-and-testing/40759) for more help or discussion.

**Comment by omnom62** [comment]
It seems to be broken due to this update - I am testing with an Ansible module, which is dependant on ansible.netcommon (v.8.0.0) and the module fails with FAILED! => {"changed": false, "msg": "Task failed: ActionBase._parse_returned_data() missing 1 required positional argument: 'profile'"}
netcommon/plugins/action/network.py: 341 data = self._parse_returned_data(dict_out) still uses the old signature

**Comment by omnom62** [comment]
A temp workaround from here worked

**Comment by omnom62** [comment]
It seems that the fix for upstream netcommon_cli is implemented in this release https://github.com/ansible-collections/ansible.netcommon/releases/tag/v8.4.0 - I am to test and advise

**Comment by omnom62** [comment]
Hey All,
It appears that, indeed, 8.4.0 is free of issues on 2.19 ansible-core. I have done a few tests to confirm (I will do more to see if our collection is compatible)
1. Test ansible-core 2.19 & netcommon v8.0.0
`((.venv129) ) [vyos]$ ansible-test network-integration --inventory hosts  vyos_config
Running vyos_config integration test role

PLAY [vyos] ********************************************************************

TASK [vyos_config : Run CLI tests] *********************************************

<skipped>

TASK [vyos_config : take configure backup] *************************************
[ERROR]: Task failed: ActionBase._parse_returned_data() missing 1 required positional argument: 'profile'
Origin: /home/vyos/lab/ansible/collections/ansible_collections/vyos/vyos/tests/output/.tmp/integration/vyos_config-apl8fa8n-ÅÑŚÌβŁÈ/tests/integration/targets/vyos_config/tests/cli/backup.yaml:17:3

15   with_items: "{{ backup_files.files|default([]) }}"
16
17 - name: take configure backup
     ^ column 3

fatal: [target15x]: FAILED! => {"changed": false, "msg": "Task failed: ActionBase._parse_returned_data() missing 1 required positional argument: 'profile'"}

PLAY RECAP *********************************************************************
target15x                  : ok=10   changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0   

NOTICE: To resume at this test target, use the option: --start-at vyos_config
FATAL: Command "ansible-playbook vyos_config-zmxxk0jv.yml -i inventory.networking" returned exit status 2.

`
2. Compare - ansible-core.2.19 & netcommon 8.4.0
``((.venv129) ) [vyos]$ ansible-test network-integration --inventory hosts  vyos_config
Running vyos_config integration test role

PLAY [vyos] ********************************************************************

TASK [vyos_config : Run CLI tests] *********************************************

<skipped>

TASK [vyos_config : debug] *****************************************************
ok: [target15x] => {
    "msg": "END cli/shortname.yaml on connection=ansible.netcommon.network_cli"
}

PLAY RECAP *********************************************************************
target15x                  : ok=141  changed=37   unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
`

**Comment by omnom62** [comment]
I made Claude work to figure out tests given https://docs.ansible.com/projects/ansible-core/devel/porting_guides/porting_guide_core_2.19.html and https://github.com/vyos/vyos.vyos/

Testing core features was OK
`$ ansible-playbook -i hosts -l vyos15x test129/core.yaml

PLAY [CORE-2.19 | Strict Boolean Conditionals (Data Tagging)] ********************************************************************************************************************************************

TASK [COND-01 | Correct explicit boolean — string length check] ******************************************************************************************************************************************
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: explicit length predicate returns bool"
}

TASK [COND-02 | Correct explicit boolean — is truthy test] ***********************************************************************************************************************************************
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: is truthy test returns bool"
}

TASK [COND-03 | Correct boolean var usage] ***************************************************************************************************************************************************************
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: proper bool conditionals work"
}

TASK [COND-04 | Correct — avoid quoting a template in a condition] ***************************************************************************************************************************************
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: bare bool var used correctly"
}

TASK [BOOL-01 | bool filter with recognised true string] *************************************************************************************************************************************************
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: recognised true values → True"
}

TASK [BOOL-02 | bool filter with recognised false string] ************************************************************************************************************************************************
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: recognised false values → False"
}

TASK [BOOL-03 | bool filter with None → False (was None before 2.19)] ************************************************************************************************************************************
[WARNING]: Deprecation warnings can be disabled by setting `deprecation_warnings=False` in ansible.cfg.
[DEPRECATION WARNING]: The `bool` filter coerced invalid value None (NoneType) to False. This feature will be removed from ansible-core version 2.23.
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: None | bool == False in 2.19+"
}

TASK [LAZY-01 | complex_var is defined even when nested key is not] **************************************************************************************************************************************
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: lazy templating — top-level var defined check"
}

TASK [LAZY-02 | access nested key with default correctly] ************************************************************************************************************************************************
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: nested key existence checked correctly"
}

TASK [ASYNC-01 | Launch an async task] *******************************************************************************************************************************************************************
changed: [vyos15x]

TASK [ASYNC-02 | Wait using `is finished` test plugin (2.19 correct pattern)] ****************************************************************************************************************************
FAILED - RETRYING: [vyos15x]: ASYNC-02 | Wait using `is finished` test plugin (2.19 correct pattern) (10 retries left).
changed: [vyos15x]

TASK [ASYNC-03 | Assert job completed — using test plugins not integer props] ****************************************************************************************************************************
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: async_status test plugins work correctly"
}

TASK [STAT-01 | Stat a path that does not exist] *********************************************************************************************************************************************************
ok: [vyos15x]

TASK [STAT-02 | Correct conditional — explicit .exists boolean] ******************************************************************************************************************************************
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: stat.exists used as explicit bool"
}

TASK [STAT-03 | Stat a real path] ************************************************************************************************************************************************************************
ok: [vyos15x]

TASK [STAT-04 | failed_when with explicit boolean — correct pattern] *************************************************************************************************************************************
changed: [vyos15x]

TASK [STROPT-01 | None value passed to a string option becomes empty string] *****************************************************************************************************************************
ok: [vyos15x] => {
    "msg": "Value is: ''"
}

TASK [STROPT-02 | Assert None coerced to empty str via template] *****************************************************************************************************************************************
ok: [vyos15x] => {
    "changed": false,
    "msg": "PASS: None coercion patterns verified"
}

TASK [BRKCON-01 | Document ALLOW_BROKEN_CONDITIONALS config key] *****************************************************************************************************************************************
ok: [vyos15x] => {
    "msg": "To temporarily downgrade broken-conditional ERRORS to warnings, set:\n  ANSIBLE_ALLOW_BROKEN_CONDITIONALS=warning\nor in ansible.cfg:\n  [defaults]\n  allow_broken_conditionals = warning\nThis will become an error permanently in a future release.\n"
}

TASK [TRACE-01 | Document new traceback env var] *********************************************************************************************************************************************************
ok: [vyos15x] => {
    "msg": "New in 2.19: ANSIBLE_DISPLAY_TRACEBACK controls traceback output.\nValid values: always, never, error (default), warning, deprecation\nCombine: ANSIBLE_DISPLAY_TRACEBACK=error,warning\nExample: ANSIBLE_DISPLAY_TRACEBACK=always ansible-playbook site.yml\n"
}

TASK [SSH-01 | Document SSH password_mechanism change] ***************************************************************************************************************************************************
ok: [vyos15x] => {
    "msg": "2.19 change: SSH connection plugin now defaults to SSH_ASKPASS\ninstead of sshpass for password authentication.\nTo revert to sshpass, set in ansible.cfg or inventory:\n  [ssh_connection]\n  password_mechanism = sshpass\nOr as env var: ANSIBLE_SSH_PASSWORD_MECHANISM=sshpass\n"
}

TASK [VAULT-01 | Document EncryptedString type change] ***************************************************************************************************************************************************
ok: [vyos15x] => {
    "msg": "2.19 change: AnsibleVaultEncryptedUnicode is replaced by EncryptedString.\nCustom plugins checking for AnsibleVaultEncryptedUnicode type must be\nupdated to use the new EncryptedString type.\nImport path: from ansible.utils.encryptedstring import EncryptedString\n"
}

PLAY [CORE-2.19 | Summary Report] ************************************************************************************************************************************************************************

TASK [SUMMARY | All 2.19 compatibility checks complete] **************************************************************************************************************************************************
ok: [vyos15x] => {
    "msg": "╔══════════════════════════════════════════════════════════════╗\n║         ansible-core 2.19 Compatibility Test Summary        ║\n╠══════════════════════════════════════════════════════════════╣\n║  COND    Strict boolean conditionals          ✓ TESTED      ║\n║  BOOL    bool filter coercion deprecation     ✓ TESTED      ║\n║  LAZY    Lazy/nested templating behaviour     ✓ TESTED      ║\n║  ASYNC   async_status is finished/started     ✓ TESTED      ║\n║  STAT    stat explicit boolean attrs          ✓ TESTED      ║\n║  STROPT  None→empty str in string options     ✓ TESTED      ║\n║  BRKCON  ALLOW_BROKEN_CONDITIONALS cfg        ✓ DOCUMENTED  ║\n║  TRACE   ANSIBLE_DISPLAY_TRACEBACK            ✓ DOCUMENTED  ║\n║  SSH     password_mechanism=SSH_ASKPASS       ✓ DOCUMENTED  ║\n║  VAULT   EncryptedString type change          ✓ DOCUMENTED  ║\n╚══════════════════════════════════════════════════════════════╝"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************
vyos15x                    : ok=23   changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 `

**Comment by omnom62** [comment]
Claude output
<html><head></head><body><h2>Analysis: <code>vyos.vyos</code> compatibility with ansible-core 2.19 — <code>src</code> template rendering</h2>
<h3>Summary</h3>
<p>This issue documents findings from a codebase analysis of <code>vyos/vyos.vyos</code> in relation to the <code>src</code>-as-Jinja2-template regression introduced by ansible-core 2.19 and fixed in <code>ansible.netcommon</code> PR <a href="https://github.com/ansible-collections/ansible.netcommon/pull/743">#743</a>.</p>
<hr>
<h3>Findings</h3>
<h4>1. <code>vyos.vyos</code> has no action plugin for <code>vyos_config</code></h4>
<p>The <code>vyos/vyos.vyos</code> repository contains no <code>plugins/action/</code> directory. There is no <code>vyos_config</code> action plugin in the collection. The collection structure relevant to this issue is:</p>
<pre><code>vyos/vyos.vyos/
└── plugins/
    ├── cliconf/vyos.py        # VyOS CLI conf plugin
    ├── modules/vyos_config.py # the module itself
    ├── module_utils/...
    └── terminal/vyos.py       # terminal settings
    # NO plugins/action/ directory
</code></pre>
<p><code>vyos_config</code> inherits its action plugin entirely from <code>ansible.netcommon/plugins/action/network.py</code>. The <code>src</code> template rendering fix in PR #743 is therefore <strong>fully within netcommon's jurisdiction</strong> — no changes are required to <code>vyos.vyos</code> collection code itself.</p>
<h4>2. The <code>vyos_config</code> module is passive with respect to <code>src</code></h4>
<p>From <code>plugins/modules/vyos_config.py</code>, the <code>get_candidate()</code> function simply receives whatever the action layer passes:</p>
<pre><code class="language-python">def get_candidate(module):
    contents = module.params["src"] or module.params["lines"]
    if module.params["src"]:
        contents = contents.splitlines()  # operates on already-received string
        ...
    return contents
</code></pre>
<p>The module has no awareness of whether <code>src</code> content was Jinja2-rendered or not. Under the broken 2.19 behaviour (without PR #743), <code>get_candidate()</code> received raw <code>{{ variable }}</code> text and pushed those literal strings to the device.</p>
<h4>3. The official documentation advertises Jinja2 <code>src</code> support</h4>
<p>The <code>DOCUMENTATION</code> block in <code>vyos_config.py</code> explicitly states:</p>
<blockquote>
<p><em>"The source config file can include Jinja2 template variables."</em></p>
</blockquote>
<p>The <code>EXAMPLES</code> block shows:</p>
<pre><code class="language-yaml">- name: render a Jinja2 template onto the VyOS router
  vyos.vyos.vyos_config:
    src: vyos_template.j2
</code></pre>
<p>Any user who followed the official module documentation is directly affected by the regression.</p>
<hr>
<h3>Impact matrix</h3>

Usage pattern | 2.18 | 2.19 without PR #743 | 2.19 with PR #743 | After Jan 2028
-- | -- | -- | -- | --
src: plain.cfg (no Jinja2) | ✅ | ✅ | ✅ | ✅
src: file.j2 (with {{ vars }}) | ✅ | ❌ Raw Jinja2 sent to device | ⚠️ Works + deprecation warning | ❌
lines: [...] | ✅ | ✅ | ✅ | ✅
lines: "{{ lookup('template', 'f.j2') }}" | ✅ | ✅ | ✅ | ✅


<p>The <code>❌</code> in the <em>After Jan 2028</em> column reflects the netcommon deprecation notice: <code>src</code>-as-Jinja2-template rendering will be removed in January 2028.</p>
<hr>
<h3>Required actions</h3>
<h4>Immediate — ensure the fix is present</h4>
<pre><code class="language-bash">ansible-galaxy collection install ansible.netcommon --upgrade
</code></pre>
<p>Confirm the installed version includes PR #743 (merged 2026-01-12).</p>
<h4>Before January 2028 — migrate <code>src: *.j2</code> calls</h4>
<p><strong>Option A — <code>lookup</code> (preferred, future-proof):</strong></p>
<pre><code class="language-yaml">- name: Apply config from Jinja2 template
  vars:
    rendered: "{{ lookup('ansible.builtin.template', 'templates/vyos.j2') }}"
  vyos.vyos.vyos_config:
    lines: "{{ rendered.splitlines() | select | list }}"
</code></pre>
<p><strong>Option B — pre-render to a plain file:</strong></p>
<pre><code class="language-yaml">- name: Render template to plain file
  ansible.builtin.template:
    src: templates/vyos.j2
    dest: /tmp/{{ inventory_hostname }}_vyos.cfg
  delegate_to: localhost

- name: Apply pre-rendered plain config
  vyos.vyos.vyos_config:
    src: /tmp/{{ inventory_hostname }}_vyos.cfg
</code></pre>
<h4>Audit your codebase</h4>
<pre><code class="language-bash">grep -rn "vyos_config" . --include="*.yml" --include="*.yaml" -l \
  | xargs grep -l "src:"
</code></pre>
<p>Any result referencing a <code>.j2</code> file, or any file known to contain <code>{{ }}</code> expressions, requires migration to one of the patterns above.</p>
<hr>
<h3>References</h3>
<ul>
<li>ansible-core 2.19 porting guide: https://docs.ansible.com/ansible-core/devel/porting_guides/porting_guide_core_2.19.html</li>
<li><code>ansible.netcommon</code> compatibility tracking issue: ansible-collections/ansible.netcommon#698</li>
<li><code>ansible.netcommon</code> fix PR: ansible-collections/ansible.netcommon#743</li>
</ul></body></html>## Analysis: `vyos.vyos` compatibility with ansible-core 2.19 — `src` template rendering

### Summary

This issue documents findings from a codebase analysis of `vyos/vyos.vyos` in relation to the `src`-as-Jinja2-template regression introduced by ansible-core 2.19 and fixed in `ansible.netcommon` PR [[#743](https://github.com/ansible-collections/ansible.netcommon/pull/743)](https://github.com/ansible-collections/ansible.netcommon/pull/743).

---

### Findings

#### 1. `vyos.vyos` has no action plugin for `vyos_config`

The `vyos/vyos.vyos` repository contains no `plugins/action/` directory. There is no `vyos_config` action plugin in the collection. The collection structure relevant to this issue is:

```
vyos/vyos.vyos/
└── plugins/
    ├── cliconf/vyos.py        # VyOS CLI conf plugin
    ├── modules/vyos_config.py # the module itself
    ├── module_utils/...
    └── terminal/vyos.py       # terminal settings
    # NO plugins/action/ directory
```

`vyos_config` inherits its action plugin entirely from `ansible.netcommon/plugins/action/network.py`. The `src` template rendering fix in PR #743 is therefore **fully within netcommon's jurisdiction** — no changes are required to `vyos.vyos` collection code itself.

#### 2. The `vyos_config` module is passive with respect to `src`

From `plugins/modules/vyos_config.py`, the `get_candidate()` function simply receives whatever the action layer passes:

```python
def get_candidate(module):
    contents = module.params["src"] or module.params["lines"]
    if module.params["src"]:
        contents = contents.splitlines()  # operates on already-received string
        ...
    return contents
```

The module has no awareness of whether `src` content was Jinja2-rendered or not. Under the broken 2.19 behaviour (without PR #743), `get_candidate()` received raw `{{ variable }}` text and pushed those literal strings to the device.

#### 3. The official documentation advertises Jinja2 `src` support

The `DOCUMENTATION` block in `vyos_config.py` explicitly states:

> *"The source config file can include Jinja2 template variables."*

The `EXAMPLES` block shows:

```yaml
- name: render a Jinja2 template onto the VyOS router
  vyos.vyos.vyos_config:
    src: vyos_template.j2
```

Any user who followed the official module documentation is directly affected by the regression.

---

### Impact matrix

| Usage pattern | 2.18 | 2.19 without PR #743 | 2.19 with PR #743 | After Jan 2028 |
|---|---|---|---|---|
| `src: plain.cfg` (no Jinja2) | ✅ | ✅ | ✅ | ✅ |
| `src: file.j2` (with `{{ vars }}`) | ✅ | ❌ Raw Jinja2 sent to device | ⚠️ Works + deprecation warning | ❌ |
| `lines: [...]` | ✅ | ✅ | ✅ | ✅ |
| `lines: "{{ lookup('template', 'f.j2') }}"` | ✅ | ✅ | ✅ | ✅ |

The `❌` in the _After Jan 2028_ column reflects the netcommon deprecation notice: `src`-as-Jinja2-template rendering will be removed in January 2028.

---

### Required actions

#### Immediate — ensure the fix is present

```bash
ansible-galaxy collection install ansible.netcommon --upgrade
```

Confirm the installed version includes PR #743 (merged 2026-01-12).

#### Before January 2028 — migrate `src: *.j2` calls

**Option A — `lookup` (preferred, future-proof):**

```yaml
- name: Apply config from Jinja2 template
  vars:
    rendered: "{{ lookup('ansible.builtin.template', 'templates/vyos.j2') }}"
  vyos.vyos.vyos_config:
    lines: "{{ rendered.splitlines() | select | list }}"
```

**Option B — pre-render to a plain file:**

```yaml
- name: Render template to plain file
  ansible.builtin.template:
    src: templates/vyos.j2
    dest: /tmp/{{ inventory_hostname }}_vyos.cfg
  delegate_to: localhost

- name: Apply pre-rendered plain config
  vyos.vyos.vyos_config:
    src: /tmp/{{ inventory_hostname }}_vyos.cfg
```

#### Audit your codebase

```bash
grep -rn "vyos_config" . --include="*.yml" --include="*.yaml" -l \
  | xargs grep -l "src:"
```

Any result referencing a `.j2` file, or any file known to contain `{{ }}` expressions, requires migration to one of the patterns above.

---

### References

- ansible-core 2.19 porting guide: https://docs.ansible.com/ansible-core/devel/porting_guides/porting_guide_core_2.19.html
- `ansible.netcommon` compatibility tracking issue: ansible-collections/ansible.netcommon#698
- `ansible.netcommon` fix PR: ansible-collections/ansible.netcommon#743

**Comment by omnom62** [comment]
@gaige Need your comment here.
It appears the collection will be compatible to ansible-core2.19+ given the recent ansible.netcommon (starting 8.4.0) as our collection just leverage upstream action plugins

**Comment by gaige** [comment]
Sounds good. Glad to hear we're finally able to move forward on this!

**Comment by omnom62** [comment]
@gaige @sever-sever @dmbaturin - anyone wants more tests, or we are ok to close the issue?

**Comment by sever-sever** [comment]
> [@gaige](https://github.com/gaige) [@sever-sever](https://github.com/sever-sever) [@dmbaturin](https://github.com/dmbaturin) - anyone wants more tests, or we are ok to close the issue?

@omnom62 I'm OK to close it. If any errors occur, they will be fixed.
Thanks
